version: '3.7'
services:
  django:
    build: .
    expose:
      - 8000
    volumes:
      - static:/usr/src/app/static
    environment:
      DEBUG: 'false'
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static:/usr/src/app/static
    ports:
      - 80:80
    links:
      - django

volumes:
  static:
