version: '3.7'
services:
  django:
    build: .
    expose:
      - 8000
    volumes:
      - static:/usr/src/app/static
    environment:
      DEBUG: 'false'
    depends_on:
      - postgres
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static:/usr/src/app/static
    ports:
      - 80:80
    links:
      - django
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data



volumes:
  static:
  pgdata:
