# Generated by Django 2.2.6 on 2019-10-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('priority', models.PositiveSmallIntegerField(choices=[(0, 'Высокий'), (1, 'Средний'), (2, 'Низкий')], verbose_name='Приоритет')),
                ('estimation', models.DurationField(verbose_name='Планируемое время')),
                ('spent_time', models.DurationField(verbose_name='Затраченное время')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'План'), (0, 'В процессе'), (0, 'Готово')], verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
