# Generated by Django 2.2.6 on 2019-10-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='spent_time',
            field=models.DurationField(default='00:00:00', verbose_name='Затраченное время'),
        ),
    ]
