# Generated by Django 2.2.6 on 2019-10-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20191010_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'План'), (0, 'В процессе'), (0, 'Готово')], default=0, verbose_name='Статус'),
        ),
    ]
