# Generated by Django 2.2.6 on 2019-10-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20191010_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'План'), (1, 'В процессе'), (2, 'Готово')], default=0, verbose_name='Статус'),
        ),
    ]
